### ISSUE TITLE
moving object at high mach number

### ISSUE THREAD

**Issue by lchn1** [wanglican/Ffowcs-Williams-and-Hawkings-Equations#2]
Hi,

Very thanks for your share first.
I haven't read it much more at the moment, so I have a question that whether this can deal with moving source and high mach number?

Thanks very much.

**Comment by wanglican** [comment]
>  I have a question that whether this can deal with moving source and high mach number?

Yes, the FW-H equation can deal with moving sources in high subsonic Mach number. In a supersonic regime, the propagation of sound might no longer be linear.
