### ISSUE TITLE
关于等效声源面

### ISSUE THREAD

**Issue by 03112397** [wanglican/Ffowcs-Williams-and-Hawkings-Equations#3]
您好大牛，有个问题想跟您咨询一下，还望不吝赐教，就是3D的等效声源面是如何构建的呢？

**Comment by wanglican** [comment]
3D等效源面可以选择0.8-0.9倍缩放的壁面

**Comment by 03112397** [comment]
谢谢您的解惑



在 2022-03-31 10:08:37，"qiaochu" ***@***.***> 写道：

3D等效源面可以选择0.8-0.9倍缩放的壁面
